name: Update Hotspots & Deploy

on:
  schedule:
    # 每天 UTC 0 点运行（北京时间 8 点）
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITEE_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Scrape hotspots
        run: python scrape.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'Gitee Actions'
          git config --global user.email 'actions@gitee.com'
          git add data.js
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          fi

      - name: Deploy to Gitee Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GITEE_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./
          force_orphan: true
